### ISSUE TITLE
Noise trigger on leaf auto exposure mode.

### ISSUE THREAD

**Issue by afrankra** [Reveni-Matt/Camera-Tester#1] opened 2024-05-18 02:34 UTC
Setup:
-Mode: Leaf auto exposure
-FW: v1.4
-HW: Kickstarter v1?
-Camera: None, Sanity check: Canonet QL 17
-Settings: EV11 f5.6 1/60s, EV16 f11 1/500

The tester is able to measure the shutter speed and aperture of the camera on the independent modes meant for it.
But when trying to simulate an accurate auto exposure at (all?) EV values like 11, the sensor is too sensitive to background noise and triggers on touch, vibrations or what seems random noise. 
The camera is set up manually to f5.6 and 1/60s. The camera is able to accurately produce this exposure for the definition of EV 11@ISO100. 
(Pic1)
The relevant settings are also configured on the Leaf AE mode. The mode triggers then randomly or inconsistently.
(Pic2)
Increasing the EV value of the light panel from 11 to 16, the sensitivity works correctly and the exposure is also accurately measured by the tester. In this case the expected exposure is of course "wrong", since the camera does EV11 exposure while the panel outputs EV16 . But it does show that the tester can measure it, but needs more light. 

This of course is a problem for the intended use of the Leaf AE mode, where the meter would read EV 11 (scenario 1) and would choose the valid setting, but the tester would never trigger properly.
(Pic3)
Increasing the EV to 16, would trigger a different auto exposure. This is simulated in the third picture but the noise error happens agains.

This makes testing AE cameras not possible beyond EV 11 (using EV 16 to trigger). Exposure of EV 12 would require EV 17 panel light.

![IMG_20240518_041253692](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/911fc1a1-ecfa-4617-8b2a-1abdd153f83f)
![IMG_20240518_041528982](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/80ea75ad-ea2c-40da-9849-c5ae5295d749)
![IMG_20240518_042757790](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/46cbe94e-8aa4-42f0-97d0-f4814ce16adc)

**Comment by Reveni-Matt** [comment] 2024-05-18 14:52
I can see in the first photo the reading only reached 5% of max at the lowest range.  To test at EV11 you'll need to increase shutter speed and use a wider aperture.

The graph is auto-scaled which is why it looks so noisy when the light reaching the sensor is very low.

What were the numerical results that were shown after the graph shown in photo 3?

**Comment by afrankra** [comment] 2024-05-18 16:03
> I can see in the first photo the reading only reached 5% of max at the lowest range. To test at EV11 you'll need to increase shutter speed and use a wider aperture.

This is in fact a problem for an Auto Exposure mode. One cannot choose these values on 90% of point and shoot auto exposure cameras.  Although some settings might not be reasonable to achieve a specific EV exposure [ think $EV11_{ISO100} = (\frac{1}{2000}s, f1.0)$ ], other combinations are completely reasonable to test against: $EV11_{ISO100} = (\frac{1}{60}s, f5.6)$. An auto exposure camera could 100% select these settings on its own to expose the EV11 produced by the panel.
Is the lowest range (#0) the most or least sensitive? 

>To test at EV11 you'll need to increase shutter speed and use a wider aperture.

Something like $EV11_{ISO100} = (\frac{1}{500}s, f2.0)$ ? If both are exposed correctly by the camera, why would this one be detectable but the previous one not? I suppose this is just due to the auto sensitivity of the AE mode? Would having manual control of the sensitivity enable to test the first EV11 example?


> The graph is auto-scaled which is why it looks so noisy when the light reaching the sensor is very low.
> What were the numerical results that were shown after the graph shown in photo 3?

![IMG_20240518_175224677](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/fa99f92f-1b3f-4dee-a309-49a4eeac11c2)
This ^ happens when tapping or winding the camera as well as releasing the shutter or even waiting. It triggers, goes into processing, hangs and ignores the shutter release, due to using #0 and triggering (to noise?) instead of the sutter.

![IMG_20240518_175303975](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/582f481a-3bac-459b-ba1a-18a53234f983)
This ^ next example is when I spam the shutter to try and catch the window in which the sensor registers before it is triggered by noise. 

![IMG_20240518_175635302](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/8668f3ee-1e5c-42d8-b7c6-adf6709d7b73)
This ^  last one I managed to force ```#1``` Sensitivity by wrongly choosing f0.7. The graph is also not as clean as needed to measure properly I think.


Is there a way to select sensitivity manually in order to try and catch the exposure within the sensors capable sensitivity range, while still also defining the EV value?

**Comment by Reveni-Matt** [comment] 2024-05-18 20:30
Yes, #0 is most sensitive.  The readings below about 10% are difficult to determine the end of exposure.  

At f2.8 and EV 11 you probably would get a good reading.

It's unlikely an AE camera can be tested at all ranges if it won't open the aperture to maximum before extending the shutter speed.  I doubt a camera would go from 1/60 f5.6 to 1/30 5.6 instead of dropping the aperture.

It's important to understand that the light is not cumulative; from your photos, it can't get enough light at f5.6 and EV11.  Shutter speed is irrelevant.

I'll need to make a table to describe the envelope better but when you went to f2 at #0 EV11 it maxed out.  F2.8 would have worked.

**Comment by afrankra** [comment] 2024-05-18 20:59
Sadly f2.8 did not work. If I understand correctly the tester wont be able to test AE cameras then. A table detailing which f stops are measurable at which EV would help. Not that it would help with point and shoots and AE modes. 
Could we still get an option to manually set sensitivity in the future? This would kind of help hack a measurement when the camera requires it. 
Again, 1/60 + f5.6 is a totally normal set of settings.

> f2 at #0 EV11 it maxed out.

Sadly the sensor would still trigger with background noise. It only trigger when spamming it trying to catch it before noise triggers it.

**Comment by afrankra** [comment] 2024-05-18 22:53
![image](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/b1f70f52-83fe-41af-b7ba-14aa0d5ab652)
After testing the ISO 100 AE mode settings ^ of the common Canon AE1, I can confirm that the tester is capable of capturing the settings on ```#1``` and  ```#2```. Sadly the default for these setups is ```#0```.  The ```#0``` will always trigger on noise before a correct capture of the shutter can be done. 

See the attached [video](https://we.tl/t-xKv0tpYeLL). Maybe I got a defective unit? I am quite confident that a firmware change to choose the sensitivity number independent of f and EV will resolve the problem. Currently In the video you can see me choose such a low F on the tester, so that the number goes from 0 to 1. You can see me trying the shutter multiple times without success of recording it, since the noise triggered and hangs the systems. Only  after forcing a ```#1``` sensitivity, I can record the shutter.

**Comment by Reveni-Matt** [comment] 2024-05-19 22:32
I'm not sure what's happening there with the mechanical jostling. 

Not sure if your video was recorded with audio but for some reason I can't get any to play.

Is the sensor cable plugged in securely?  

If you go into leaf mode and set the aperture to f45 or something you should be able to force range 0 as shown like in AE mode, and see if it has the same sensitivity issue.

What's the green LED doing when this happens?

**Comment by afrankra** [comment] 2024-05-20 00:24
These two new [videos](https://we.tl/t-RUiXKLdNSq) have sound with the cable properly secured to the housing. The light panel is blocked by 120 backing paper. The sensor is also blocked by 120 backing paper and covered by a dark bag. The lights in the room are off.
Touches to the sensor trigger the noise. Touches to the housing or cable connection, do not. I suppose the cable within the sensor housing could trigger if a pin connection rubs (is it soldered or jst connected?).
The LED triggers, recording a measurement, as seen on the screen. The measurement can be seen as not a shutter release, but intermittent delta spikes. Perhaps it could be filtered / ignored in firmware. A shutter release would have a different 'signature'.

**Comment by Reveni-Matt** [comment] 2024-05-20 01:41
I don't think it can be a cable issue actually, because all sensitivities use the same wires.

Did you try it not on AE leaf, on just leaf?  First option after curtain shutter.  With it set to f45 it should use sensitivity 0.

Clearly you are triggering it with physical contact so the question is, is it static/capacitive interference or mechanical vibration.   Try poking the bag with sensor inside using a 30cm wooden stick?  

![Screenshot_20240519_213619_Dropbox.jpg](https://github.com/Reveni-Matt/Camera-Tester/assets/170122039/4912fd32-4d49-4e63-addf-00cc828a8e3d)

These two resistors are for the most sensitive setting.  Maybe one is loose, is my guess. Resistance across the pair should be 20 megaohms.  C4 should not be present, that is deliberate.

Can you take a photo of the sensor info shown on startup, when the sensor is in dark?  Particularly if the 5 range numbers match.

I'll try to do some experimenting but I don't know why it's vibration sensitive.  What you find by poking it with a wood stick will help narrow it down.

**Comment by Reveni-Matt** [comment] 2024-05-20 01:56
I have an idea.  I removed C4 because it wasn't proving necessary with parasitic capacitance from the MOSFETs doing the job.  I didn't have an issue with C4 removed but maybe yours is oscillating when you touch it in #0 sensitivity. 

The solution should be a 1pF capacitor put in place on C4's location.

I'll see if I can get replication on my end by messing with things to make interference, like running a motor nearby to produce strong magnetic interference.  You poking it with a wood stick should tell me something too.

**Comment by afrankra** [comment] 2024-05-20 02:05
>I don't think it can be a cable issue actually, because all sensitivities use the same wires.
>I'll try to do some experimenting but I don't know why it's vibration sensitive. What you find by poking it with a wood stick will help narrow it down.

![IMG_20240520_022729430](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/d25ba5b0-99f6-4d74-8efc-127493dc9af0)
After ^ disassembling the sensor head and fixing one of the jst connectors I noticed that one of the two error cases disappeared (remote vibrations, the connection of the brown wire was definitely lose and barely making contact, see pic ^). 

Sadly, the second failure case (touch of camera to trigger shutter or touching the sensor casing itself) still remains. After many iterations, with housing, screws, no screws, gloves, touching ground, etc; I came to the discovery, that the housing itself + the middle sensor is somehow triggering when exposed to my body, either heat or electromagnetic noise at sensitivity ```#0```. 
See the [video ](https://we.tl/t-12I7zUv5BC) for the example of this. The video was taken with the cabled fixed. It no longer responds to vibrations, just touch. 

>Did you try it not on AE leaf, on just leaf? First option after curtain shutter. With it set to f45 it should use sensitivity 0.

Yes, See previous videos for sensitivity 0 with f45. Both Leaf shutter and AE Leaf are still triggering to touch of the housing and depending on the camera, touch of the camera too. Trigger shutter with a wooden/plastic stick, doesnt cause the noise false trigger. 

>Can you take a photo of the sensor info shown on startup, when the sensor is in dark? Particularly if the 5 range numbers match.

After turning it off and on a couple of times, they do match most of the time. All `Ranges` are now (after cable fix) between 8 and 13.

>I'll try to do some experimenting but I don't know why it's vibration sensitive. What you find by poking it with a wood stick will help narrow it down.

Experimenting on why it triggers to touch at `Sensitivity/Range #0` could be more interesting. I think the vibration was just the cable. Although no rush!

>These two resistors are for the most sensitive setting. Maybe one is loose, is my guess. Resistance across the pair should be 20 megaohms. C4 should not be present, that is deliberate.

I can confirm that each one measured 10ohm, C4 is not there.

I still want to emphasize that even with a working Range of `#0`, It is difficult to test normal AE combinations of shutter speed and aperture, as shown on [this table](https://github.com/Reveni-Matt/Camera-Tester/issues/1#issuecomment-2119022659)

**Comment by Reveni-Matt** [comment] 2024-05-20 14:13
So it appears your touch, likely your body as a capacitively coupled antenna, is causing the sensor circuit to oscillate.

Adding a capacitor of 1pF or so should resolve this issue.  How do you want to do this?  I could send you the part if you can solder it to the C4 location.  Or I can order you the part from a vendor and have it sent directly to you.

I need to make a matrix of apertures and panel EVs.  It's possible, if the AE camera has the behaviour of reducing the shutter speed before going to the widest aperture, or the max aperture is low like f5.6, that the AE camera can't be tested at all light levels.

In my experience the AE system opts to max out the aperture before dropping shutter speeds below 1/60 because of shake and blur issues.

Off the top of my head the low end is around EV7 at f1.4, EV8 at f2, EV9 at f2.8 etc. When #0 is working properly.

**Comment by afrankra** [comment] 2024-05-20 15:20
Hi Matt, Thank you for the feedback.

> So it appears your touch, likely your body as a capacitively coupled antenna, is causing the sensor circuit to oscillate.
> Adding a capacitor of 1pF or so should resolve this issue. How do you want to do this? I could send you the part if you can solder it to the C4 location. Or I can order you the part from a vendor and have it sent directly to you.

I have some laying around, but not surface mounted ones. Ceramic most probably. Not sure if ceramic will serve the intended purpose tho. I will see if I can find it or procure it locally. 

> I need to make a matrix of apertures and panel EVs. It's possible, if the AE camera has the behaviour of reducing the shutter speed before going to the widest aperture, or the max aperture is low like f5.6, that the AE camera can't be tested at all light levels.

Wouldn't a Firmware update (eventually), where the sensitivity can be chosen manually (instead of implicitly through the f-stop approximation / or in addition to the current method) help too?

> In my experience the AE system opts to max out the aperture before dropping shutter speeds below 1/60 because of shake and blur issues.

I sadly do not think this assumption is generally correct. It will limit the usability of the tester a lot.

![image](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/9265da4a-6f5a-4a52-b488-a107162cd913)

The picture shown above ^ is from the canon AE1 . Maybe others can show other service manuals. But most AE setups couple shutter speed and aperture linearly, where decreasing 1 EV, decreases both aperture and shutter speed in half stops. 
I think a simple independent manual sensitivity setting can will go a long way here.


As general experience for information: The only way I found to consistently test at sensitivity `#0`, is by using the eraser of a pencil from far away in subdue light. Any ambient light might trigger it. My body hovering over the camera + tester can trigger it too. And touching or the metal camera will also trigger it.  For context, I am at 410 m (1,350 ft) above sea level, so I dont think its elevation dependent either. Maybe a firmware shutter event detection filter could help too.
I will try manually soldering a small 1pF ceramic capacitor. Is anyone else also having this problem?

**Comment by Reveni-Matt** [comment] 2024-05-20 15:45
No other reports of issues of any kind.  

If the AE system works from EV17 to EV11, changing ISO works appropriately, is testing to some other limit particularly necessary?

A non-SMT capacitor soldered in place is fine. Closest to 1pF that you have.  Higher pF values will begin to affect the triggering speed.  I hope this will work but since you're the only person with this issue so far, I am curious why it isn't more common if this proves to be the solution.

I'll make a sensitiviy adjustment test firmware shortly.

**Comment by Reveni-Matt** [comment] 2024-05-20 16:22
I just did some experimenting, I was seeing the same thing you were if I touched the location of the photodiode with my finger.  It wasn't an issue when the camera is in place.  I added a 1pF cap on C4 and it helped, I had to put a 3pF on there to get it to stop completely.  On sensitivity 0, it will trigger if I hover my finger within a few mm of the photodiode pins on the PCB. If I touch the pins the noise from that causes it to trigger at any sensitivity level.

Yours must just happen to be more sensitive than this one because it was triggering with just contact on the camera. 

The brown wire you fixed is for one of the curtain detectors and isn't relevant to the issue.

**Comment by afrankra** [comment] 2024-05-20 16:28
> I added a 1pF cap on C4 and it helped, I had to put a 3pF on there to get it to stop completely.

Do you recommend the 3pF over the 1pF? 

> On sensitivity 0, it will trigger if I hover my finger within a few mm of the photodiode pins on the PCB. 

This is my experience too. I suppose the EM on my desk is quite intense.

**Comment by Reveni-Matt** [comment] 2024-05-20 16:37
the EM at my place is pretty high too, I'm sure.  Computers, monitors, all kinds of equipment around.  Humidity is low 40s.

Depending on what you have around, try 1pF or go up to 5pF.  You can put multiple in parallel to get a higher pF value.

Working on that firmware right now, I'll upload something for you to try soon.  I've got my sensor giving good AE readings down to f16 at EV11.

**Comment by Reveni-Matt** [comment] 2024-05-20 17:49
OK here's a test firmware (1.5T) which has improved analysis of the data, should be better at ignoring any noise spikes after the camera triggers.  In AE LEAF mode, pressing left/right buttons will directly change the sensitivity as shown at the bottom.  Ignore the aperture near the top right.

I'm getting a decent analysis even if only 4.4% of the sensor range is used.

EDIT ok I can't put firmwares in comments.  I'll put it on the other page.

**Comment by afrankra** [comment] 2024-05-20 19:17
Thank you for the new firmware! **_Without_** the capacitor upgrade + `Firmware 1.5T` the `AE LEAF mode` now does not immediately react to the noise as before. Sometimes the screen goes blank and shows no graph when I approach my hand to the sensor housing. The LED still turns on, the screen goes blank, but the response time is much better. I can now trigger the shutter properly even after FW filters out noise events ( like my with my hand on the housing). This all without the capacitor installed tho. I managed to trigger okish reponses **_sometimes_** at f11 and EV11. I am sure this will improve with the capacitor then.
I will report the behavior once I obtain the capacitor upgrade.

**Comment by Reveni-Matt** [comment] 2024-05-20 21:30
If you need to buy a capacitor, the SMT size is 0603 (1608 metric) ceramic, 6.3V or higher.

**Comment by afrankra** [comment] 2024-05-21 12:18
![image](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/0cf1568f-3b81-4c2a-a06c-ec9605c1a80a)

With a 2.2pF ^ ceramic non-surface capacitor I managed to make EV11 up to f5.6 work. 
I also tried a 50pF surface mounted (all I had around), which limited me to only f2 at EV11.
A 1pF would probable allow for f8, but I dont got one and the soldering job is quite difficult due to the compactness of the sensor head. Kind of scared of wearing of the soldering pads on the sensor PCB.
With  the combination of the capacitor 2.2pF and firmware update, the EV11 at f5.6 will do (EV 11 being a bright indoors or dark strong shadow areas). 

The sensitivity to noise oscillations / high frequencies at `#0` is annoying: Touching the camera when the sensor housing (SLS 3D Printed carbon?) is properly seated into the film plane hole, triggers noise at `#0` (this is being filtered out by the firmware tho, which is good). I managed to regulate it by not having the sensor housing touching the camera, leaving a gap having it hover near it, but not touching. Kinda janky but it works.

I wonder if adding some sort of EM cage/coating on the sensor housing could help. 

> I'm getting a decent analysis even if only 4.4% of the sensor range is used.

Is this with 5pF + Firmware 1.5T ?

> Working on that firmware right now, I'll upload something for you to try soon. I've got my sensor giving good AE readings down to f16 at EV11.

I was hoping to get here too. But odd that I only get f5.6. That is 3 less Stops.

**Comment by Reveni-Matt** [comment] 2024-05-21 13:23
> Touching the camera when the sensor housing (SLS 3D Printed carbon?) is properly seated into the film plane hole, triggers noise at #0

I haven't been able to replicate this.  Even on a sensor with no capacitor, I only have interference when I touch it on the front.  The material is MJF nylon and is non-conductive.

> Is this with 5pF + Firmware 1.5T ?

I've done it with only 3pf and 1.5T.  

> I was hoping to get here too. But odd that I only get f5.6. That is 3 less Stops.

It seems to be down to some small variances in sensor heads, but mostly the particular EM situation in your area.  In my case, if I put a piece of paper between the sensor front and my finger, it reduces the effect range by a lot.  When I touch a piece of sheet metal that's in the way it completely removes it.

shielding the sensor could help even if the shield isn't grounded.  You could try wrapping it in aluminum foil, open a hole at the front for the photodiode, and see how the behaviour changes. It may clear it up.  If it works, lining the interior with foil may solve it in a more permanent way.

**Comment by afrankra** [comment] 2024-05-21 14:02
Covering the entire sensor head on aluminum Foil and touching it on the same location as before, still triggers the noise filter.
If I  ground myself to one of the screws of the tester itself when touching the aluminum Foil, then it wont trigger. 
If I remove the aluminum foil and touch the (are you sure?) non-conductive housing and ground myself to the same screw on the tester housing, it wont trigger noise filtering either.
The aluminum Foil doesnt help. but grounding myself to the housing does.

**Comment by afrankra** [comment] 2024-05-21 14:07
![image](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/29c509a9-4c05-4af7-adcb-51c18caaa016)

I think the solution is to just use a grounding strap to any of the exposed metals on the housing, could be the rods, screws or even the blind mounts.

**Comment by Reveni-Matt** [comment] 2024-05-21 14:12
The spec'd electrical characteristics are "Dielectirc strength 2.8kV/mm; Volume Resitivity 10^14 ohm-cm"

An ESD band should work based on what you tested, yes.  Another option would be to tie to the circuit ground inside the sensor head, maybe have an exposed wire which can touch the camera under test in a place that is consistently metallic like film rails.  Or this wire could serve as a place for you to rest a finger while you use the tester. 

Another option would be to cover the inside of the head with foil and connect the foil to the circuit ground in the head, would probably work with no added hassles when operating the machine.

It's very interesting that you're the only person who has reported any issue with this so far.  Maybe people aren't using the AE modes.

**Comment by afrankra** [comment] 2024-05-21 16:23
> Another option would be to cover the inside of the head with foil and connect the foil to the circuit ground in the head, would probably work with no added hassles when operating the machine.

Is the head not grounded to the machine?

> An ESD band should work based on what you tested, yes. Another option would be to tie to the circuit ground inside the sensor head, maybe have an exposed wire which can touch the camera under test in a place that is consistently metallic like film rails. Or this wire could serve as a place for you to rest a finger while you use the tester.

I can rest my finger on the metal rods. 

> It's very interesting that you're the only person who has reported any issue with this so far. Maybe people aren't using the AE modes.

Maybe I am the only not  grounded by not touching the machine. You did corroborate the interference on the sensor tho. Mine is just more sensitive.

**Comment by afrankra** [comment] 2024-05-21 18:36
> Another option would be to cover the inside of the head with foil and connect the foil to the circuit ground in the head, would probably work with no added hassles when operating the machine.

I tested continuity of the sensor head against the tester housing ground and could not find a connecting pin to test this.

**Comment by Reveni-Matt** [comment] 2024-05-21 19:20
> Is the head not grounded to the machine?

Yes it's grounded but it's picking up interference still, must be going directly to a component(s) on the surface.  If the foil was inside the head and connecting to the circuit ground via the inside of the head, it would shield it.

> Maybe I am the only not grounded by not touching the machine. You did corroborate the interference on the sensor tho. Mine is just more sensitive.

If I touch the sensor jig, I have no interference, even on a capacitor with no sensor installed.  When touching bare metal on the Tester, I only get the green LED to turn on if I touch the exposed sensor head circuit board directly, and only in certain spots where there isn't a circuit ground on the PCB in the area I'm touching (if my finger touches a grounded spot, it doesn't cause interference even if I'm also touching a sensitive spot).

Maybe you are right that more people touch the machine more when working, like they have their hand all over the sensor jig or are resting a hand on some part of the jig.

**Comment by Reveni-Matt** [comment] 2024-05-21 19:25
> I tested continuity of the sensor head against the tester housing ground and could not find a connecting pin to test this.

if you're talking about the shell of the cable, it's only grounded when plugged into the Camera Tester.  Pin 5 of the connector inside the head is circuit ground, and there are many locations where the ground planes on the board are stitched together with vias, I've circled them in the attached picture.

![2024-05-21 15 20 57-1](https://github.com/Reveni-Matt/Camera-Tester/assets/170122039/c3f69df9-e7d2-478f-a39d-fbfddb0937f8)

**Comment by afrankra** [comment] 2024-05-22 09:00
>if you're talking about the shell of the cable, it's only grounded when plugged into the Camera Tester. Pin 5 of the connector inside the head is circuit ground, and there are many locations where the ground planes on the board are stitched together with vias, I've circled them in the attached picture.

I think we have a misunderstanding. Pin 5 is not grounded to metal frame of the tester. There is no continuity between it and any of the metal rods or silver metal screws. 
I mention this, because those exposed metal parts (silver screws or metal rods) are the "ground" I am touching to "ground" myself to the machine and avoid producing interference. 

> Yes it's grounded but it's picking up interference still, must be going directly to a component(s) on the surface. If the foil was inside the head and connecting to the circuit ground via the inside of the head, it would shield it.

I also see no continuity between the metal cable connector and the silver screws. 
Shouldn't the circuit ground and case ground be the same? (I am not an EE fyi.)

> If the foil was inside the head and connecting to the circuit ground via the inside of the head, it would shield it.

Shielding the sensor head internally is difficult for me. I am afraid of short circuiting the head with aluminum foil. The back end I can cover, but the front plate would be more difficult due to the tight tolerances for the sensors.

Just my understanding until now:
-The machine operator causes noise to trigger on the machine at sensitivity range `#0` when touching certain areas of the sensor head. 
-Grounding the operator of the machine to the machine exterior helped in my case.
-Not sure if the capacitor mod is necessary at all when  proper grounding of the person using the machine is maintained.
-The capacitor mod by itself helped, but did not resolve the problem, although limits the FSTOP that can be used at `#0`.
-Shielding the sensor head (not sure how to do it safely) could? entirely solve the problem.
-The firmware filtering and independent choice of sensitivity also help the operator.

I think we can close the Issue from my part. Grounding oneself is still an ok solution on my book. A hardware / machine only solution by having the sensor shielded / grounded would have been convenient and better, but not sure how feasible it is now that the machines are out the door. Perhaps for a V2.

**Comment by Reveni-Matt** [comment] 2024-05-22 14:40
>  Pin 5 is not grounded to metal frame of the tester. There is no continuity between it and any of the metal rods or silver metal screws.

Actually it is the other way around.  There's no connection to true earth through the wall adapter, and the enclosure is left floating from circuit ground.  However, touching the metal is impacting your electrical behavior as a capacitor/antenna, and reducing the impact you have on the circuit.

My tests show that my effect on the sensor head with no capacitor installed goes away if I touch either the ground plane area of the sensor head PCB or the metal rigging of the tester, the issue is eliminated either way.

You can touch a circuit ground externally on the Tester if you touch the metal ring around the flash input, that will connect your finger to the circuit ground.

> Shielding the sensor head internally is difficult for me. I am afraid of short circuiting the head with aluminum foil. The back end I can cover, but the front plate would be more difficult due to the tight tolerances for the sensors.

Yes, understandable.

> Just my understanding until now:
-The machine operator causes noise to trigger on the machine at sensitivity range #0 when touching certain areas of the sensor head.

Yes, or even just being near it.  I can trigger the issue by hovering my finger near the PCB.

> -Grounding the operator of the machine to the machine exterior helped in my case.

It seems to resolve it in all cases.  The added metal is altering the "human antenna" enough to prevent it.

> -The capacitor mod by itself helped, but did not resolve the problem, although limits the FSTOP that can be used at #0.

I didn't see similar issues with the range being harmed, I can get consistent triggers at f11 on EV11 and occasional triggers on f16 at EV11.

I did some tests with varying amounts of contact:

![2024-05-22 09 41 51 (Custom)](https://github.com/Reveni-Matt/Camera-Tester/assets/170122039/9e86fe17-89ac-45e8-8335-2f74b11fa553)

We need a connection between the Tester PCB and the metal frame, closing the circuit and making any part of the metal jig a good place to touch to remove the noise.  A simple way to add the connection that I just tested is to open the enclosure, remove a nut that holds the board in place, put a toothed lockwasher on, and tighten it back down, making sure the teeth of the lockwasher bite into the surface of the board and reach the copper underneath the green insulator coating.  This creates the connection from the board to the screw and on to the rest of the enclosure, I'm reading a couple of ohms of resistance from the end of the sensor jig to the metal shroud on the sensor connection port.

![2024-05-22 10 32 47](https://github.com/Reveni-Matt/Camera-Tester/assets/170122039/74adca91-4a3e-49c1-aae8-2b77bba7e07e)

A metal-housing for the sensor, or lining the interior with conductive material, would probably be the best and most complete solution.

**Comment by afrankra** [comment] 2024-05-22 15:13
> Actually it is the other way around. There's no connection to true earth through the wall adapter, and the enclosure is left floating from circuit ground. However, touching the metal is impacting your electrical behavior as a capacitor/antenna, and reducing the impact you have on the circuit.

Oh thank you for this feedback. I see your examples and they seem similar to my experience!

> My tests show that my effect on the sensor head with no capacitor installed goes away if I touch either the ground plane area of the sensor head PCB or the metal rigging of the tester, the issue is eliminated either way.

So I could remove the capacitor installed if I do the grounding of circuit -> housing right?

> A simple way to add the connection that I just tested is to open the enclosure, remove a nut that holds the board in place, put a toothed lockwasher on, and tighten it back down, making sure the teeth of the lockwasher bite into the surface of the board and reach the copper underneath the green insulator coating. 

Do you have recommendations on how to open it safely to add it? Could I solder a wire to ground and wrap it to the nut?
I can try and venture inside the tester if needed for the grounding mod. This would solve the issue for me at least.

**Comment by Reveni-Matt** [comment] 2024-05-22 16:54
> So I could remove the capacitor installed if I do the grounding of circuit -> housing right?

If I recall correctly, you had better low-light performance before the capacitor was installed?  What shutter speeds was that at?  If the capacitor is affecting the reaction time of the sensor (which is expected, a small reduction in the speed at which the signal and rise and fall) then at a short speed, 1/500 or 1/1000, there's possibility that the signal isn't reaching a high enough level to activate the detector circuit. 

In the sensor head, there is the analog circuit which is putting out the light level as a voltage.  Attached to this voltage, there is a circuit which, if the signal reaches 3.3% of maximum, quickly tells the Tester's processor that a shutter trigger is occurring and start recording the analog voltage level.

> Do you have recommendations on how to open it safely to add it? Could I solder a wire to ground and wrap it to the nut?

I can try and venture inside the tester if needed for the grounding mod. This would solve the issue for me at least.

Yes, remove the 4 feet on the side of the Tester with the sticker.  Pull the bottom off by pulling the two halves away, starting at the side with the USB port.  Locate the unused data port "J7", one of the four holes there is marked GND.  Solder a wire into there, then wrap the other end around the nearby screw.  You can trap it under the nut if you want.  You can solder the wire into a loop.  It's an M3 nut, you could add a 2nd nut on top of the existing one to sandwich your wire loop if you wanted.

Take your meter and check the resistance from your wire to the sensor jig and see it's got a good connection, under 10 ohms.

**Comment by afrankra** [comment] 2024-05-22 20:31
![IMG_20240522_220905377](https://github.com/Reveni-Matt/Camera-Tester/assets/5390192/90df29f0-cff4-4621-bb63-3d771a8a2a8f)

I can say it works. Is there a risk of shock or anything like that by touching the frame once grounded to the circuit?

**Comment by Reveni-Matt** [comment] 2024-05-22 21:25
Great.

No risk, it's the same as any other wall adapter powered device.  

Thanks for your help in working out this issue and resolution.

I'll be working on a public release version of V1.5 to send soon.

**Comment by afrankra** [comment] 2024-05-22 21:38
> Thanks for your help in working out this issue and resolution.
> I'll be working on a public release version of V1.5 to send soon.

Thank you for your help! I see that with AEL + 1.5T the plot is sometimes skipped at f8>f11+ but is correctly identified. Only the shutter speed is not correctly displayed, although it was still clear to a 'human'.

**Closed as completed** 2024-05-23 03:16 UTC

**Comment by Reveni-Matt** [comment] 2024-05-23 17:53
I added a new firmware V1.5T2 to the repo, check it out.  It has some new menu stuff and a curtain time and velocity display I'm trying out.  Let me know what you think.

**Comment by afrankra** [comment] 2024-05-23 18:59
Hi, Thank you. Some Feedback:
-The Light Meter Mode and leaf shutter Menu has a 3rd ghost menu item under the K value.
-Leaf shutter mode seems to not react to sensor changes <>
-AE Curtain mode seems to not react to sensor changes <>
-Curtain Shutter mode seems amazing!

**Comment by Reveni-Matt** [comment] 2024-05-23 22:20
Thanks, I'll put up a new one.

**Comment by afrankra** [comment] 2024-05-24 12:13
Seems to work great.
Does the removal of the setting: lens / no lens on some of the modes (dont remember which)  happened because of the manual sensitivity setting?

**Comment by Reveni-Matt** [comment] 2024-05-24 14:06
Yes it felt redundant because all that option did was force sensitivity #3.
